.TH CLIMAN 1 2022-09-15 0.3.1

.SH NAME
climan \- A file based HTTP client

.SH SYNOPSIS
.B climan
[\fB\-hrvV\fR]
[\fB\-\-color\fR \fIWHEN\fR]
[\fB\-i\fR \fINUM\fR]
[\fB\-t\fR \fIMS\fR]
FILE

.SH DESCRIPTION
.B climan
makes a request from the given FILE, which should follow \fIRFC9110\fR standards, with all environment variables in the format of ${KEY} being replaced.

.SH OPTIONS
.TP
.BR \-\-color " " \fIWHEN
Whether to use escape sequences. Possible values are auto, never, and always.
.TP
.BR \-h ", " \-\-help
Show help and exit.
.TP
.BR \-i ", " \-\-index " " \fINUM
Determine which request to make. Negative values start from the end.
.TP
.BR \-r ", " \-\-raw
Do not format response body.
.TP
.BR \-t ", " \-\-timeout " " \fIMS
Set maximum time for a request to take. Zero means no timeout.
.TP
.BR \-v ", " \-\-verbose
output verbosely.
.TP
.BR \-V ", " \-\-version
Show version and exit.

.SH AUTHOR
Amirabbas Fazelinia <utilyre@proton.me>

.SH SEE ALSO
\fBcurl\fR(1)
