name: Continues Deployment

on:
  push:
    tags: [v*.*.*]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    steps:
      - name: Checkout version tag
        uses: actions/checkout@v3
      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - name: Download dependencies
        run: go mod download
      - name: Compile source code
        run: |
          mkdir -p climan-${{ matrix.os }}-${{ matrix.arch }}/bin
          env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o climan-${{ matrix.os }}-${{ matrix.arch }}/bin
      - name: Archive files
        run: |
          tar -czf climan-${{ matrix.os }}-${{ matrix.arch }}.tar.gz climan-${{ matrix.os }}-${{ matrix.arch }}
          zip -r climan-${{ matrix.os }}-${{ matrix.arch }}.zip climan-${{ matrix.os }}-${{ matrix.arch }}
      - name: Create artifact assets
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: |
            climan-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
            climan-${{ matrix.os }}-${{ matrix.arch }}.zip
  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Move archives to cwd
        run: |
          mv dist/*/*.tar.gz dist/*/*.zip .
          rm -r dist
      - name: Compute checksums
        run: sha256sum *.tar.gz *.zip > sha256sums.txt
      - name: Create new release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: CLIMAN ${{ github.ref_name }}
          body: |
            ## 📦 Installation

            Download `sha256sums.txt` as well as an appropriate archive that
            suits your operating system and architecture. Then follow the
            instructions of your operating system below.

            **NOTE**: Make sure to replace `[ARCH]` with your corresponding
            architecture.

            ### 🐧 Linux

            1. Verify checksums

               ```bash
               sha256sum -c sha256sums.txt
               ```

               **NOTICE**: You might see `No such file or directory` warning
               which is fine as long as there is an `OK` in front of the
               archive you've downloaded.

            2. Extract the downloaded archive.

               - Gzip

               ```bash
               tar -xzf climan-linux-[ARCH].tar.gz
               ```

               - Zip

               ```bash
               unzip climan-linux-[ARCH].zip
               ```

            3. Install the included files

               ```bash
               cd climan-linux-[ARCH]
               sudo install -Dm755 bin/climan /usr/local/bin/climan
               ```

            ### 🍎 MacOS

            1. Verify checksums

               ```bash
               sha256sum -c sha256sums.txt
               ```

               **NOTICE**: You might see `No such file or directory` warning
               which is fine as long as there is an `OK` in front of the
               archive you've downloaded.

            2. Extract the downloaded archive.

               - Gzip

               ```bash
               tar -xzf climan-darwin-[ARCH].tar.gz
               ```

               - Zip

               ```bash
               unzip climan-darwin-[ARCH].zip
               ```

            3. Install the included files

               ```bash
               cd climan-darwin-[ARCH]
               sudo install -Dm755 bin/climan /usr/local/bin/climan
               ```

            ### 🐌 Windows

            1. Verify checksums.

               - Gzip

               ```powershell
               Get-FileHash -Algorithm SHA256 -Path climan-windows-[ARCH].tar.gz
               ```

               - Zip

               ```powershell
               Get-FileHash -Algorithm SHA256 -Path climan-windows-[ARCH].zip
               ```

               Now check if output of the previous command matches the
               corresponding line of `sha256sums.txt`.

            2. Extract the downloaded archive.

            3. Append `%USERPROFILE%\bin` to `Path` environment variable.

            4. Install the included files

               ```powershell
               Set-Location -Path climan-windows-[ARCH]
               Copy-Item -Path bin\climan.exe -Destination %USERPROFILE%\bin\climan.exe
               ```
          files: |
            *.tar.gz
            *.zip
            sha256sums.txt
