name: Continues Deployment

on:
  push:
    tags: [v*.*.*]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Checkout version tag
        uses: actions/checkout@v3
      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - name: Download dependencies
        run: go mod download
      - name: Compile source code
        run: |
          mkdir doc
          mkdir man
          mkdir bin

          mv LICENSE doc
          gzip -9 man/*/*
          env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o bin
      - name: Archive files
        run: |
          mkdir -p climan-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}/doc
          mkdir -p climan-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}/man
          mkdir -p climan-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}/bin

          mv doc/* climan-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}/doc
          mv man/* climan-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}/man
          mv bin/* climan-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}/bin

          tar -czf climan-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz climan-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}
      - name: Create artifact assets
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: climan-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Move archives to cwd
        run: |
          mv dist/*/*.tar.gz .
          rm -r dist
      - name: Compute checksums
        run: sha256sum *.tar.gz > sha256sums.txt
      - name: Create new release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: CLIMAN ${{ github.ref_name }}
          body: |
            ## 📦 Installation

            Download `sha256sums.txt` as well as an appropriate archive that
            suits your operating system and architecture. Then follow the
            instructions of your operating system below.

            **NOTE**: Make sure to replace `[ARCH]` with your corresponding
            architecture.

            ### 🐧 Linux

            1. Verify checksums

               ```bash
               sha256sum --ignore-missing -c sha256sums.txt
               ```

            2. Extract the downloaded archive.

               ```bash
               tar -xzf climan-${{ github.ref_name }}-linux-[ARCH].tar.gz
               ```

            ### 🍎 MacOS

            1. Verify checksums

               ```bash
               sha256sum -c sha256sums.txt
               ```

               **NOTICE**: You might see `No such file or directory` warnings
               which is fine as long as there is an `OK` in front of the
               archive you've downloaded.

            2. Extract the downloaded archive.

               ```bash
               tar -xzf climan-${{ github.ref_name }}-darwin-[ARCH].tar.gz
               ```
          files: |
            *.tar.gz
            sha256sums.txt
