name: Continues Deployment

on:
  push:
    tags: [v*.*.*]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    steps:
      - name: Checkout version tag
        uses: actions/checkout@v3
      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - name: Download dependencies
        run: go mod download
      - name: Compile source code
        run: |
          mkdir -p climan-${{ matrix.os }}-${{ matrix.arch }}/bin
          env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o climan-${{ matrix.os }}-${{ matrix.arch }}/bin
      - name: Archive files
        run: |
          tar -czf climan-${{ matrix.os }}-${{ matrix.arch }}.tar.gz climan-${{ matrix.os }}-${{ matrix.arch }}
          zip -r climan-${{ matrix.os }}-${{ matrix.arch }}.zip climan-${{ matrix.os }}-${{ matrix.arch }}
      - name: Create artifact assets
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: |
            climan-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
            climan-${{ matrix.os }}-${{ matrix.arch }}.zip
  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*/*.tar.gz
            dist/*/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
