name: Continues Deployment

on:
  push:
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd, amd64, arm, arm64]
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-go@latest
        with:
          go-version: 1.18
      - name: Compilation
        run: env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o output
      - name: Distribution
        run: |
          mkdir -p dist
          tar --remove-files -czf dist/climan-${{ matrix.os }}-${{ matrix.arch }}.tar.gz output
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@latest
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
