name: Continues Deployment

on:
  push:
    tags: [v*.*.*]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Compilation
        run: env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o output
      - name: Distribution
        run: |
          mkdir -p dist
          tar --remove-files -czf dist/climan-${{ matrix.os }}-${{ matrix.arch }}.tar.gz output
  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
