name: Continues Deployment

on:
  push:
    tags: [v*.*.*]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Checkout version tag
        uses: actions/checkout@v3
      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Compile source code
        run: env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o climan
      - name: Archive binary
        run: tar -czf climan-${{ matrix.os }}-${{ matrix.arch }}.tar.gz climan
      - name: Create artifact assets
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: climan-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
